'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Certificate_Logging
    Public Property Identifier As Integer
    Public Property RecipientName As String
    Public Property RecipientEmailAddress As String
    Public Property RecipientManagerEmailAddress As String
    Public Property SenderName As String
    Public Property SenderEmailAddress As String
    Public Property CertificateMessage As String
    Public Property CertificateDate As Nullable(Of Date)
    Public Property CertificateType As String
    Public Property EmailSubject As String
    Public Property EmailBody As String
    Public Property EmailSent As Nullable(Of Boolean)
    Public Property DateCreated As Nullable(Of Date)
    Public Property LoggedOnUser As String
    Public Property ExecutiveTeamConsideration As Nullable(Of Boolean)

End Class
