'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _default1

    '''<summary>
    '''aspnetForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspnetForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''TestMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TestMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MessageOutput control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageOutput As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MessageOutput2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MessageOutput2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pnlForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cmbTemplates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTemplates As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''chkExecutiveTeamConsideration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExecutiveTeamConsideration As Global.DevExpress.Web.ASPxCheckBox

    '''<summary>
    '''txtRecipientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecipientName As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRecipientEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecipientEmailAddress As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtRecipientManagerEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecipientManagerEmailAddress As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txtMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMessage As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''txtCounter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCounter As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblSenderNameHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenderNameHeader As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSenderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenderName As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSenderEmailAddressHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenderEmailAddressHeader As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''lblSenderEmailAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenderEmailAddress As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''deDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deDate As Global.DevExpress.Web.ASPxDateEdit

    '''<summary>
    '''btnCreateCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCertificate As Global.DevExpress.Web.ASPxButton
End Class
